# Cella 1 - Importazioni:

In [48]:
# Importazione delle librerie necessarie
import os
import re
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from decimal import Decimal
from connessioni import get_mysql_connection

# Configurazione pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Cella 2 - Carica dati da raw_data in DataFrame:

In [49]:
# Connessione al database
conn = get_mysql_connection()

# Carica tutti i dati da raw_data in un DataFrame
query = "SELECT * FROM raw_data"
df_raw = pd.read_sql(query, conn)

conn.close()

print(f"Dataset caricato: {df_raw.shape[0]} righe, {df_raw.shape[1]} colonne")
print("\n Prime 5 righe:")
df_raw.head()

Dataset caricato: 165 righe, 40 colonne

 Prime 5 righe:

C:\Users\Utente\AppData\Local\Temp\ipykernel_7068\1275688268.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_raw = pd.read_sql(query, conn)

,id,timestamp,email_indirizzo,email_app,consenso,contesto,età,genere,area_geo,anni_esperienza,Item_1,Item_2,Item_3,Item_4,Item_5,Item_6,Item_7,Item_8,Item_9,Item_10,Item_11,Item_12,Item_13,Item_14,Item_15,Item_16,Item_17,Item_18,Item_19,Item_20,Item_21,Item_22,Item_23,Item_24,Item_25,Item_26,Item_27,Item_28,Item_29,Item_30
0,1,2026-01-24 13:59:40,None,None,Accetto,Entrambi,24,Femmina,Nord Italia,5,4.0,5.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,1.0,1.0,2.0,2.0,4.0,5.0,5.0,Durante gli esami e se devo interagire con gli...
1,2,2026-01-24 14:51:07,None,None,Accetto,Di studio,26,Femmina,Nord Italia,7 anni,4.0,5.0,3.0,4.0,3.0,4.0,3.0,2.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,5.0,4.0,4.0,4.0,2.0,4.0,1.0,3.0,3.0,5.0,2.0,2.0,2.0,4.0,Durante gli esami
2,3,2026-01-24 14:51:23,None,None,Accetto,Di lavoro,26,Maschio,Nord Italia,5 anni,3.0,4.0,3.0,4.0,4.0,4.0,5.0,3.0,2.0,1.0,4.0,4.0,2.0,2.0,2.0,4.0,2.0,4.0,5.0,5.0,3.0,5.0,1.0,1.0,4.0,2.0,5.0,4.0,5.0,Interazione con persone (clienti)
3,4,2026-01-24 14:54:35,None,None,Accetto,Entrambi,26,Femmina,Nord Italia,5,2.0,4.0,3.0,5.0,5.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,5.0,3.0,5.0,3.0,2.0,5.0,3.0,3.0,2.0,3.0,2.0,1.0,3.0,L’esame
4,5,2026-01-24 15:00:36,None,None,Accetto,Di studio,22,Femmina,Nord Italia,2,3.0,2.0,3.0,4.0,4.0,3.0,2.0,2.0,3.0,1.0,4.0,3.0,3.0,3.0,2.0,4.0,3.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,4.0,3.0,3.0,2.0,4.0,"Durante il tirocinio, quando devo mettere effe..."

# Cella 3 - Esplora il dataset:

In [50]:
# Informazioni sul dataset
print("📋 Informazioni sul dataset:\n")
df_raw.info()

print("\n📊 Valori nulli per colonna:")
print(df_raw.isnull().sum())

#NOTA: DA SISTEMARE DATATYPE

📋 Informazioni sul dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 40 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               165 non-null    int64
 1   timestamp        165 non-null    datetime64[ns]
 2   email_indirizzo  2 non-null      object
 3   email_app        12 non-null     object
 4   consenso         165 non-null    object
 5   contesto         164 non-null    object
 6   età              164 non-null    object
 7   genere           164 non-null    object
 8   area_geo         164 non-null    object
 9   anni_esperienza  164 non-null    object
 10  Item_1           164 non-null    float64
 11  Item_2           164 non-null    float64
 12  Item_3           164 non-null    float64
 13  Item_4           164 non-null    float64
 14  Item_5           164 non-null    float64
 15  Item_6           156 non-null    float64
 16  Item_7           156 non-null    float64
 17  Item_8           156 non-null    float64
 18  Item_9           157 non-null    float64
 19  Item_10          155 non-null    float64
 20  Item_11          152 non-null    float64
 21  Item_12          152 non-null    float64
 22  Item_13          151 non-null    float64
 23  Item_14          150 non-null    float64
 24  Item_15          150 non-null    float64
 25  Item_16          164 non-null    float64
 26  Item_17          164 non-null    float64
 27  Item_18          164 non-null    float64
 28  Item_19          164 non-null    float64
 29  Item_20          164 non-null    float64
 30  Item_21          164 non-null    float64
 31  Item_22          164 non-null    float64
 32  Item_23          164 non-null    float64
 33  Item_24          164 non-null    float64
 34  Item_25          164 non-null    float64
 35  Item_26          164 non-null    float64
 36  Item_27          164 non-null    float64
 37  Item_28          164 non-null    float64
 38  Item_29          164 non-null    float64
 39  Item_30          90 non-null     object
dtypes: datetime64[ns](1), float64(29), int64(1), object(9)
memory usage: 51.7+ KB

📊 Valori nulli per colonna:
id                   0
timestamp            0
email_indirizzo    163
email_app          153
consenso             0
contesto             1
età                  1
genere               1
area_geo             1
anni_esperienza      1
Item_1               1
Item_2               1
Item_3               1
Item_4               1
Item_5               1
Item_6               9
Item_7               9
Item_8               9
Item_9               8
Item_10             10
Item_11             13
Item_12             13
Item_13             14
Item_14             15
Item_15             15
Item_16              1
Item_17              1
Item_18              1
Item_19              1
Item_20              1
Item_21              1
Item_22              1
Item_23              1
Item_24              1
Item_25              1
Item_26              1
Item_27              1
Item_28              1
Item_29              1
Item_30             75
dtype: int64

# Cella 4 - Funzione pulizia età:

In [51]:
# Funzione per pulire e convertire l'età
def pulisci_eta(eta_raw):
    """
    Converte l'età da testo a intero.
    FILTRO: Solo età tra 19 e 30 anni
    """
    if pd.isna(eta_raw) or eta_raw == '':
        return None
    
    eta_raw = eta_raw.lower()
    
    for i in ['anni', 'anno']:
        eta_raw = eta_raw.replace(i, '')
        eta_int = int(eta_raw)
        if eta_int < 19 or eta_int > 30:
            return None
        return eta_int
    
    return None
# CONTROLLARE DATATYPE ETA
# Applica la funzione al DataFrame
df_raw['età_pulita'] = df_raw['età'].apply(pulisci_eta)

print("Test pulizia età:\n")
print(df_raw[['età', 'età_pulita']].head(10))

# VERIFICARE QUANTE RIGHE SONO STATE ESCLUSE
print(f"\nRighe da escludere (età fuori range 19-30): {df_raw['età_pulita'].isna().sum()}")

Test pulizia età:

  età  età_pulita
0  24        24.0
1  26        26.0
2  26        26.0
3  26        26.0
4  22        22.0
5  26        26.0
6  26        26.0
7  24        24.0
8  20        20.0
9  30        30.0

Righe da escludere (età fuori range 19-30): 18

# Cella 5 - Funzione pulizia anni esperienza:

In [52]:
def pulisci_anni_esperienza(exp_raw):
    """Converte anni esperienza in formato anni.mesi"""
    if pd.isna(exp_raw) or exp_raw == '':
        return None
    
    exp_str = str(exp_raw).lower().replace(',', '.')
    
    totale_anni = 0
    totale_mesi = 0
    
    # Caso 1: "X anni"
    anni_match = re.findall(r'(\d+)\s*ann[oi]', exp_str)
    for a in anni_match:
        totale_anni += int(a)
    
    # Caso 2: "Y mesi"
    mesi_match = re.findall(r'(\d+(?:\.\d+)?)\s*mes[ei]', exp_str)
    for m in mesi_match:
        mesi_val = float(m)
        if mesi_val < 1:
            totale_mesi += int(mesi_val * 10)  # 0.7 mesi → 7 mesi (interpreta come 0.X anni)
        else:
            totale_mesi += int(mesi_val)
    
    # Caso 3: "mezzo"
    if 'mezzo' in exp_str or 'mezza' in exp_str:
        totale_mesi += 6
    
    # Caso 4: Numeri decimali (se non ha trovato "anni" o "mesi")
    if totale_anni == 0 and totale_mesi == 0:
        # Trova TUTTI i numeri decimali e sommali
        decimali = re.findall(r'\d+\.\d+', exp_str)
        
        for dec in decimali:
            val = float(dec)
            anni_parte = int(val)
            mesi_parte = int(round((val - anni_parte) * 10))  # Parte decimale × 10
            
            totale_anni += anni_parte
            totale_mesi += mesi_parte
    
    # Caso 5: Solo interi
    if totale_anni == 0 and totale_mesi == 0:
        numeri = re.findall(r'\b(\d+)\b', exp_str)
        if numeri:
            totale_anni = int(numeri[0])
    
    # Normalizza
    if totale_mesi >= 12:
        totale_anni += totale_mesi // 12
        totale_mesi = totale_mesi % 12
    
    # Formato finale
    return float(f"{totale_anni}.{totale_mesi:02d}")  # :02d garantisce sempre 2 cifre


# Test
print("Test:\n")
tests = ['1,1', '0,8', '9,5', '0,7 mesi', '2.5 lavoro di cui 0.5 studio']
for t in tests:
    print(f"'{t}' → {pulisci_anni_esperienza(t)}")

# Applica al DataFrame
df_raw['anni_esperienza_pulita'] = df_raw['anni_esperienza'].apply(pulisci_anni_esperienza)

print("\nTest su dati reali:\n")
print(df_raw[['anni_esperienza', 'anni_esperienza_pulita']].head(40))

Test:

'1,1' → 1.01
'0,8' → 0.08
'9,5' → 9.05
'0,7 mesi' → 0.07
'2.5 lavoro di cui 0.5 studio' → 2.1

Test su dati reali:

                                anni_esperienza  anni_esperienza_pulita
0                                             5                    5.00
1                                        7 anni                    7.00
2                                        5 anni                    5.00
3                                             5                    5.00
4                                             2                    2.00
5                                             8                    8.00
6                                        5 anni                    5.00
7                                             0                    0.00
8                                        2 Anni                    2.00
9                                            11                   11.00
10                                       5 anni                    5.00
11                                            8                    8.00
12                                            5                    5.00
13                                         None                     NaN
14                                            5                    5.00
15                                            5                    5.00
16                                            3                    3.00
17                                           32                   32.00
18                                           30                   30.00
19                               3 anni e mezzo                    3.06
20                                          9,5                    9.05
21                                           13                   13.00
22                                       3 anni                    3.00
23                                           10                   10.00
24                                            6                    6.00
25                                          1,1                    1.01
26                                           10                   10.00
27                                          0,8                    0.08
28                                    0.7 mesi                     0.07
29                                            7                    7.00
30                                      11 anni                   11.00
31                                            7                    7.00
32                                           10                   10.00
33                                       2 anni                    2.00
34                                            4                    4.00
35                                            5                    5.00
36  2.5 lavoro di cui 0.5 studio per magistrale                    2.10
37                                          0,4                    0.04
38                                           10                   10.00
39                                          7,5                    7.05

# Cella 6 - Pulizia incoerenze contesto:

In [53]:
# Funzione per pulire incoerenze tra contesto e risposte
def pulisci_incoerenze_items(row):
    """
    Pulisce incoerenze tra contesto e Items.
    - Se "Di studio" → Item_16-20 (lavoro) = NULL
    - Se "Di lavoro" → Item_11-15 (studio) = NULL
    - Se "Entrambi" → tutto OK
    """
    contesto = str(row['contesto']).lower()
    
    # Se contesto è "Di studio" → cancella Item_16-20
    if 'studio' in contesto and 'entrambi' not in contesto and 'lavoro' not in contesto:
        for i in range(16, 21):  # Item_16 a Item_20
            row[f'Item_{i}'] = None
    
    # Se contesto è "Di lavoro" → cancella Item_11-15
    elif 'lavoro' in contesto and 'entrambi' not in contesto and 'studio' not in contesto:
        for i in range(11, 16):  # Item_11 a Item_15
            row[f'Item_{i}'] = None
    
    return row


# Analisi PRIMA della pulizia
print("📊 PRIMA della pulizia incoerenze:\n")
for idx, row in df_raw.head(10).iterrows():
    contesto = row['contesto']
    studio_count = sum(1 for i in range(11, 16) if pd.notna(row[f'Item_{i}']))
    lavoro_count = sum(1 for i in range(16, 21) if pd.notna(row[f'Item_{i}']))
    print(f"ID {row['id']} | Contesto: {contesto:15s} | Studio: {studio_count}/5 | Lavoro: {lavoro_count}/5")

# Applica la pulizia
df_raw = df_raw.apply(pulisci_incoerenze_items, axis=1)

print("\n📊 DOPO la pulizia incoerenze:\n")
for idx, row in df_raw.head(10).iterrows():
    contesto = row['contesto']
    studio_count = sum(1 for i in range(11, 16) if pd.notna(row[f'Item_{i}']))
    lavoro_count = sum(1 for i in range(16, 21) if pd.notna(row[f'Item_{i}']))
    print(f"ID {row['id']} | Contesto: {contesto:15s} | Studio: {studio_count}/5 | Lavoro: {lavoro_count}/5")

📊 PRIMA della pulizia incoerenze:

ID 1 | Contesto: Entrambi        | Studio: 5/5 | Lavoro: 5/5
ID 2 | Contesto: Di studio       | Studio: 5/5 | Lavoro: 5/5
ID 3 | Contesto: Di lavoro       | Studio: 5/5 | Lavoro: 5/5
ID 4 | Contesto: Entrambi        | Studio: 5/5 | Lavoro: 5/5
ID 5 | Contesto: Di studio       | Studio: 5/5 | Lavoro: 5/5
ID 6 | Contesto: Di lavoro       | Studio: 5/5 | Lavoro: 5/5
ID 7 | Contesto: Di lavoro       | Studio: 5/5 | Lavoro: 5/5
ID 8 | Contesto: Disoccupazione  | Studio: 5/5 | Lavoro: 5/5
ID 9 | Contesto: Di lavoro       | Studio: 5/5 | Lavoro: 5/5
ID 10 | Contesto: Entrambi        | Studio: 5/5 | Lavoro: 5/5

📊 DOPO la pulizia incoerenze:

ID 1 | Contesto: Entrambi        | Studio: 5/5 | Lavoro: 5/5
ID 2 | Contesto: Di studio       | Studio: 5/5 | Lavoro: 0/5
ID 3 | Contesto: Di lavoro       | Studio: 0/5 | Lavoro: 5/5
ID 4 | Contesto: Entrambi        | Studio: 5/5 | Lavoro: 5/5
ID 5 | Contesto: Di studio       | Studio: 5/5 | Lavoro: 0/5
ID 6 | Contesto: Di lavoro       | Studio: 0/5 | Lavoro: 5/5
ID 7 | Contesto: Di lavoro       | Studio: 0/5 | Lavoro: 5/5
ID 8 | Contesto: Disoccupazione  | Studio: 5/5 | Lavoro: 5/5
ID 9 | Contesto: Di lavoro       | Studio: 0/5 | Lavoro: 5/5
ID 10 | Contesto: Entrambi        | Studio: 5/5 | Lavoro: 5/5

In [54]:
df_raw.head(20)

,id,timestamp,email_indirizzo,email_app,consenso,contesto,età,genere,area_geo,anni_esperienza,Item_1,Item_2,Item_3,Item_4,Item_5,Item_6,Item_7,Item_8,Item_9,Item_10,Item_11,Item_12,Item_13,Item_14,Item_15,Item_16,Item_17,Item_18,Item_19,Item_20,Item_21,Item_22,Item_23,Item_24,Item_25,Item_26,Item_27,Item_28,Item_29,Item_30,età_pulita,anni_esperienza_pulita
0,1,2026-01-24 13:59:40,None,None,Accetto,Entrambi,24,Femmina,Nord Italia,5,4.0,5.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,1.0,1.0,2.0,2.0,4.0,5.0,5.0,Durante gli esami e se devo interagire con gli...,24.0,5.00
1,2,2026-01-24 14:51:07,None,None,Accetto,Di studio,26,Femmina,Nord Italia,7 anni,4.0,5.0,3.0,4.0,3.0,4.0,3.0,2.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,3.0,3.0,5.0,2.0,2.0,2.0,4.0,Durante gli esami,26.0,7.00
2,3,2026-01-24 14:51:23,None,None,Accetto,Di lavoro,26,Maschio,Nord Italia,5 anni,3.0,4.0,3.0,4.0,4.0,4.0,5.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,4.0,5.0,5.0,3.0,5.0,1.0,1.0,4.0,2.0,5.0,4.0,5.0,Interazione con persone (clienti),26.0,5.00
3,4,2026-01-24 14:54:35,None,None,Accetto,Entrambi,26,Femmina,Nord Italia,5,2.0,4.0,3.0,5.0,5.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,5.0,3.0,5.0,3.0,2.0,5.0,3.0,3.0,2.0,3.0,2.0,1.0,3.0,L’esame,26.0,5.00
4,5,2026-01-24 15:00:36,None,None,Accetto,Di studio,22,Femmina,Nord Italia,2,3.0,2.0,3.0,4.0,4.0,3.0,2.0,2.0,3.0,1.0,4.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,4.0,3.0,3.0,2.0,4.0,"Durante il tirocinio, quando devo mettere effe...",22.0,2.00
5,6,2026-01-24 15:30:50,None,None,Accetto,Di lavoro,26,Maschio,Nord Italia,8,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,2.0,2.0,1.0,2.0,4.0,4.0,5.0,5.0,2.0,1.0,3.0,Durate una attivtà di aggiornamento sistema al...,26.0,8.00
6,7,2026-01-24 17:26:08,None,None,Accetto,Di lavoro,26,Femmina,Nord Italia,5 anni,3.0,2.0,1.0,3.0,4.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,4.0,3.0,2.0,2.0,1.0,4.0,3.0,2.0,4.0,1.0,1.0,2.0,Situazioni in cui devo affrontare colloqui che...,26.0,5.00
7,8,2026-01-24 19:31:04,None,None,Accetto,Disoccupazione,24,Maschio,Centro Italia,0,4.0,4.0,3.0,5.0,4.0,3.0,2.0,3.0,4.0,2.0,4.0,3.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,4.0,3.0,3.0,1.0,2.0,2.0,1.0,4.0,4.0,5.0,None,24.0,0.00
8,9,2026-01-24 19:45:55,None,None,Accetto,Di lavoro,20,Femmina,Sud Italia e Isole,2 Anni,5.0,5.0,5.0,5.0,5.0,4.0,3.0,4.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,3.0,3.0,4.0,3.0,5.0,3.0,1.0,1.0,5.0,4.0,1.0,1.0,5.0,Si sempre,20.0,2.00
9,10,2026-01-24 20:45:41,None,None,Accetto,Entrambi,30,Maschio,Nord Italia,11,2.0,1.0,2.0,5.0,5.0,2.0,4.0,1.0,3.0,5.0,2.0,3.0,4.0,5.0,3.0,2.0,2.0,2.0,5.0,2.0,3.0,4.0,3.0,4.0,3.0,5.0,5.0,4.0,5.0,La parte esecutiva dei progetti da fare a casa...,30.0,11.00
10,11,2026-01-24 22:32:56,None,None,Accetto,Di lavoro,27,Maschio,Centro Italia,5 anni,3.0,4.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,4.0,3.0,3.0,4.0,3.0,3.0,2.0,2.0,2.0,2.0,4.0,5.0,5.0,None,27.0,5.00
11,12,2026-01-24 22:58:56,None,None,Accetto,Di lavoro,25,Maschio,Sud Italia e Isole,8,3.0,1.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,4.0,1.0,2.0,5.0,"Ho ansia nel cucinare per me stesso, dando il ...",25.0,8.00
12,13,2026-01-25 00:28:57,None,None,Accetto,Di studio,23,Maschio,Nord Italia,5,2.0,1.0,2.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,4.0,5.0,3.0,5.0,1.0,1.0,2.0,None,23.0,5.00
13,14,2026-01-25 00:53:05,None,None,Non accetto (in questo caso il questionario no...,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
14,15,2026-01-25 01:54:32,None,None,Accetto,Di studio,18,Maschio,Nord Italia,5,1.0,2.0,1.0,1.0,4.0,2.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,4.0,1.0,5.0,1.0,1.0,5.0,no,NaN,5.00
15,16,2026-01-25 10:55:29,None,None,Accetto,Entrambi,30,Maschio,Sud Italia e Isole,5,3.0,5.0,5.0,3.0,4.0,4.0,4.0,3.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,4.0,2.0,3.0,3.0,4.0,4.0,4.0,Di studio sicuramente l'esame orale è quello c...,30.0,5.00
16,17,2026-01-25 11:08:12,None,None,Accetto,Di studio,21,Maschio,Nord Italia,3,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,3.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,3.0,3.0,5.0,4.0,2.0,3.0,3.0,None,21.0,3.00
17,18,2026-01-25 11:15:38,None,None,Accetto,Di lavoro,56,Femmina,Nord Italia,32,3.0,4.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,Sinceramente no,NaN,32.00
18,19,2026-01-25 11:22:25,None,None,Accetto,Di lavoro,57,Femmina,Sud Italia e Isole,30,2.0,4.0,4.0,4.0,4.0,4.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,3.0,3.0,1.0,3.0,4.0,4.0,4.0,1.0,1.0,3.0,None,NaN,30.00
19,20,2026-01-25 12:31:25,None,None,Accetto,Di lavoro,29,Femmina,Nord Italia,3 anni e mezzo,3.0,3.0,4.0,4.0,4.0,3.0,2.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,3.0,3.0,3.0,2.0,3.0,3.0,4.0,3.0,3.0,2.0,4.0,Quando sbaglio qualcosa e devo rendere conto d...,29.0,3.06

# Cella 7 - Filtra per età e crea DataFrame pulito:

In [55]:
# Filtra solo righe con età valida (19-30)
df_clean = df_raw[df_raw['età_pulita'].notna()].copy()

# Sostituisci le colonne pulite
df_clean['età'] = df_clean['età_pulita'].astype(int)
df_clean['anni_esperienza'] = df_clean['anni_esperienza_pulita']

# Rimuovi colonne temporanee
df_clean = df_clean.drop(columns=['età_pulita', 'anni_esperienza_pulita'])

print(f"Dati puliti:")
print(f"   - Righe prima: {len(df_raw)}")
print(f"   - Righe dopo (età 19-30): {len(df_clean)}")
print(f"   - Righe escluse: {len(df_raw) - len(df_clean)}")

print("\nStatistiche età dopo pulizia:")
print(df_clean['età'].describe())

print("\nPrime 5 righe del DataFrame pulito:")
df_clean.head()

Dati puliti:
   - Righe prima: 165
   - Righe dopo (età 19-30): 147
   - Righe escluse: 18

Statistiche età dopo pulizia:
count    147.000000
mean      23.809524
std        3.492327
min       19.000000
25%       21.000000
50%       24.000000
75%       26.000000
max       30.000000
Name: età, dtype: float64

Prime 5 righe del DataFrame pulito:

,id,timestamp,email_indirizzo,email_app,consenso,contesto,età,genere,area_geo,anni_esperienza,Item_1,Item_2,Item_3,Item_4,Item_5,Item_6,Item_7,Item_8,Item_9,Item_10,Item_11,Item_12,Item_13,Item_14,Item_15,Item_16,Item_17,Item_18,Item_19,Item_20,Item_21,Item_22,Item_23,Item_24,Item_25,Item_26,Item_27,Item_28,Item_29,Item_30
0,1,2026-01-24 13:59:40,None,None,Accetto,Entrambi,24,Femmina,Nord Italia,5.0,4.0,5.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,1.0,1.0,2.0,2.0,4.0,5.0,5.0,Durante gli esami e se devo interagire con gli...
1,2,2026-01-24 14:51:07,None,None,Accetto,Di studio,26,Femmina,Nord Italia,7.0,4.0,5.0,3.0,4.0,3.0,4.0,3.0,2.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,3.0,3.0,5.0,2.0,2.0,2.0,4.0,Durante gli esami
2,3,2026-01-24 14:51:23,None,None,Accetto,Di lavoro,26,Maschio,Nord Italia,5.0,3.0,4.0,3.0,4.0,4.0,4.0,5.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,4.0,5.0,5.0,3.0,5.0,1.0,1.0,4.0,2.0,5.0,4.0,5.0,Interazione con persone (clienti)
3,4,2026-01-24 14:54:35,None,None,Accetto,Entrambi,26,Femmina,Nord Italia,5.0,2.0,4.0,3.0,5.0,5.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,5.0,3.0,5.0,3.0,2.0,5.0,3.0,3.0,2.0,3.0,2.0,1.0,3.0,L’esame
4,5,2026-01-24 15:00:36,None,None,Accetto,Di studio,22,Femmina,Nord Italia,2.0,3.0,2.0,3.0,4.0,4.0,3.0,2.0,2.0,3.0,1.0,4.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,4.0,3.0,3.0,2.0,4.0,"Durante il tirocinio, quando devo mettere effe..."

In [56]:
df_clean.tail()

,id,timestamp,email_indirizzo,email_app,consenso,contesto,età,genere,area_geo,anni_esperienza,Item_1,Item_2,Item_3,Item_4,Item_5,Item_6,Item_7,Item_8,Item_9,Item_10,Item_11,Item_12,Item_13,Item_14,Item_15,Item_16,Item_17,Item_18,Item_19,Item_20,Item_21,Item_22,Item_23,Item_24,Item_25,Item_26,Item_27,Item_28,Item_29,Item_30
158,159,2026-03-04 13:53:52,None,None,Accetto,Di lavoro,25,Femmina,Nord Italia,6.0,3.0,3.0,2.0,2.0,4.0,3.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,4.0,3.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,Riunioni
159,160,2026-03-04 14:14:22,None,None,Accetto,Di lavoro,30,Femmina,Nord Italia,10.0,3.0,3.0,3.0,5.0,5.0,3.0,3.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,3.0,4.0,2.0,1.0,3.0,3.0,5.0,5.0,2.0,2.0,3.0,None
160,161,2026-03-04 14:14:27,None,None,Accetto,Di lavoro,29,Femmina,Nord Italia,10.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,2.0,3.0,2.0,2.0,3.0,3.0,5.0,3.0,3.0,1.0,5.0,Situazioni in cui espongo in pubblico
163,164,2026-03-05 22:16:51,None,None,Accetto,Di lavoro,29,Maschio,Nord Italia,10.0,4.0,4.0,3.0,5.0,5.0,4.0,4.0,3.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,5.0,4.0,4.0,4.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,quando mi chiedono di portare a termine qualco...
164,165,2026-03-08 11:12:21,None,giulio.serafini098@gmail.com,Accetto,Di lavoro,27,Maschio,Centro Italia,8.0,3.0,4.0,2.0,3.0,2.0,4.0,3.0,4.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,4.0,3.0,2.0,2.0,4.0,None

1) eliminnare colonna timestamp 
2) spostare valori presenti(tipo 3 o 4 indirizzo email presente, questi voglio spostare sulla colonna email_app) sul colonna email_app dal colonna email_indirizzo e poi eliminnare colonna email_indirizzo poi modifico nome email_app in email
3) età e anni_esperienza devo sostituire con colonna puliti

4) riga cosenso uguale non accetto da eliminnare e poi dopo devo eliminnare la colonna consenso
5) visto che età no serve numeri decimali vasta come interi

# Cella 8 - ELIMINA COLONNA TIMESTAMP

In [57]:
df_clean = df_clean.drop(columns=['timestamp'])
print("Colonna 'timestamp' eliminata")

Colonna 'timestamp' eliminata

# Cella 9 - UNIFICA EMAIL: email_indirizzo → email_app, poi rinomina in 'email'

In [58]:
# Sposta i valori non-null da email_indirizzo a email_app
df_clean['email_app'] = df_clean['email_app'].fillna(df_clean['email_indirizzo'])

# Elimina email_indirizzo
df_clean = df_clean.drop(columns=['email_indirizzo'])

# Rinomina email_app in email
df_clean = df_clean.rename(columns={'email_app': 'email'})

print("Email unificate: email_indirizzo + email_app → 'email'")
print(f"   - Email presenti: {df_clean['email'].notna().sum()}")

Email unificate: email_indirizzo + email_app → 'email'
   - Email presenti: 12

# Cella 10 - SOSTITUISCI ETÀ E ANNI_ESPERIENZA CON VERSIONI PULITE

In [59]:
# Età: converti in intero (già fatto in Cella 4, ma assicuriamoci)
df_clean['età'] = df_clean['età'].astype(int)

# Anni esperienza: già pulita nella colonna anni_esperienza_pulita
# (Nota: questa è già stata sostituita nella Cella 7, ma verifichiamo)
if 'anni_esperienza_pulita' in df_clean.columns:
    df_clean['anni_esperienza'] = df_clean['anni_esperienza_pulita']
    df_clean = df_clean.drop(columns=['anni_esperienza_pulita'])

print("Età e anni_esperienza aggiornate con versioni pulite")

Età e anni_esperienza aggiornate con versioni pulite

# Cella 11 - ELIMINA RIGHE CON CONSENSO = "NON ACCETTO" E POI ELIMINA COLONNA

In [60]:
righe_prima = len(df_clean)

# MODIFICARE
# Filtra solo righe dove consenso = "Accetto" (o varianti)
df_clean = df_clean[df_clean['consenso'].str.lower().str.contains('accetto', na=False)]

righe_dopo = len(df_clean)
righe_eliminate_consenso = righe_prima - righe_dopo

# Elimina la colonna consenso
df_clean = df_clean.drop(columns=['consenso'])

print(f"Righe con consenso 'non accetto' eliminate: {righe_eliminate_consenso}")
print(f"Colonna 'consenso' eliminata")

Righe con consenso 'non accetto' eliminate: 0
Colonna 'consenso' eliminata

# Cella 12 - RIEPILOGO FINALE

In [61]:
print("\n" + "="*60)
print("RIEPILOGO PULIZIE FINALI:")
print("="*60)
print(f"Righe totali dopo pulizie: {len(df_clean)}")
print(f"Colonne totali: {len(df_clean.columns)}")
print(f"\nColonne rimanenti:")
print(df_clean.columns.tolist())

print("\nPrime 5 righe del DataFrame pulito finale:")
display(df_clean.tail(40))

print("\nInfo DataFrame pulito:")
df_clean.info()

============================================================
RIEPILOGO PULIZIE FINALI:
============================================================
Righe totali dopo pulizie: 147
Colonne totali: 37

Colonne rimanenti:
['id', 'email', 'contesto', 'età', 'genere', 'area_geo', 'anni_esperienza', 'Item_1', 'Item_2', 'Item_3', 'Item_4', 'Item_5', 'Item_6', 'Item_7', 'Item_8', 'Item_9', 'Item_10', 'Item_11', 'Item_12', 'Item_13', 'Item_14', 'Item_15', 'Item_16', 'Item_17', 'Item_18', 'Item_19', 'Item_20', 'Item_21', 'Item_22', 'Item_23', 'Item_24', 'Item_25', 'Item_26', 'Item_27', 'Item_28', 'Item_29', 'Item_30']

Prime 5 righe del DataFrame pulito finale:

,id,email,contesto,età,genere,area_geo,anni_esperienza,Item_1,Item_2,Item_3,Item_4,Item_5,Item_6,Item_7,Item_8,Item_9,Item_10,Item_11,Item_12,Item_13,Item_14,Item_15,Item_16,Item_17,Item_18,Item_19,Item_20,Item_21,Item_22,Item_23,Item_24,Item_25,Item_26,Item_27,Item_28,Item_29,Item_30
121,122,None,Di lavoro,26,Maschio,Nord Italia,2.00,4.0,3.0,2.0,4.0,3.0,4.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,5.0,Situazioni nuove
122,123,None,Entrambi,25,Femmina,Nord Italia,1.00,3.0,4.0,2.0,5.0,5.0,3.0,4.0,4.0,5.0,1.0,3.0,3.0,4.0,4.0,2.0,3.0,1.0,4.0,5.0,2.0,1.0,5.0,4.0,4.0,3.0,5.0,4.0,1.0,3.0,None
123,124,None,Di studio,19,Maschio,Nord Italia,0.06,4.0,3.0,3.0,2.0,1.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,2.0,5.0,3.0,2.0,1.0,5.0,None
124,125,None,Entrambi,20,Maschio,Nord Italia,0.04,4.0,3.0,1.0,3.0,4.0,2.0,1.0,2.0,3.0,1.0,3.0,4.0,5.0,4.0,3.0,4.0,2.0,4.0,4.0,1.0,2.0,3.0,3.0,4.0,4.0,5.0,2.0,2.0,5.0,None
125,126,None,Di lavoro,24,Femmina,Nord Italia,0.06,2.0,5.0,1.0,5.0,4.0,5.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,4.0,5.0,5.0,5.0,4.0,5.0,4.0,4.0,1.0,5.0,4.0,5.0,5.0,None
126,127,None,Di lavoro,28,Femmina,Nord Italia,4.06,4.0,4.0,3.0,4.0,5.0,4.0,2.0,3.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,2.0,3.0,3.0,3.0,2.0,4.0,3.0,2.0,2.0,4.0,Quando devo affrontare progrtti nuovi e devo c...
127,128,None,Entrambi,20,Maschio,Nord Italia,2.00,3.0,4.0,3.0,2.0,4.0,4.0,3.0,2.0,2.0,1.0,4.0,3.0,2.0,4.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,4.0,3.0,3.0,4.0,2.0,2.0,4.0,None
128,129,None,Di studio,25,Maschio,Nord Italia,4.05,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,2.0,3.0,4.0,2.0,1.0,5.0,No
129,130,None,Entrambi,22,Maschio,Sud Italia e Isole,4.00,3.0,4.0,3.0,4.0,4.0,4.0,5.0,4.0,4.0,2.0,3.0,3.0,3.0,4.0,2.0,3.0,3.0,4.0,4.0,5.0,4.0,3.0,2.0,2.0,4.0,3.0,4.0,2.0,5.0,Durante un esame o quando mi viene affidata un...
130,131,None,Di lavoro,29,Maschio,Centro Italia,3.00,3.0,5.0,5.0,3.0,3.0,4.0,3.0,2.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,3.0,5.0,4.0,5.0,1.0,1.0,1.0,2.0,4.0,2.0,5.0,"L'ansia sta condizionando la mia vita ormai, g..."
131,132,None,Di studio,26,Maschio,Sud Italia e Isole,7.00,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.0,1.0,1.0,1.0,1.0,5.0,5.0,4.0,None
132,133,xferubit97@outlook.it,Di lavoro,28,Maschio,Nord Italia,9.00,3.0,3.0,1.0,3.0,4.0,3.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,3.0,2.0,4.0,3.0,2.0,2.0,2.0,4.0,4.0,3.0,4.0,1.0,3.0,3.0,2 situazioni: quando so che la reazione dell'a...
133,134,andreatab7@gmail.com,Di lavoro,22,Maschio,Nord Italia,3.00,4.0,5.0,4.0,4.0,3.0,4.0,3.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,3.0,2.0,5.0,4.0,5.0,1.0,2.0,4.0,2.0,3.0,3.0,5.0,I colloqui lavorativi in cui devi dimostrare d...
134,135,None,Di studio,23,Femmina,Nord Italia,5.00,2.0,2.0,2.0,1.0,2.0,4.0,2.0,4.0,5.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,5.0,4.0,4.0,5.0,1.0,1.0,2.0,"Non c'è una situazione specifica, di solito ri..."
135,136,None,Di studio,21,Maschio,Nord Italia,15.00,5.0,5.0,4.0,5.0,4.0,5.0,2.0,2.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,3.0,3.0,5.0,1.0,2.0,3.0,4.0,None
136,137,None,Di studio,21,Maschio,Sud Italia e Isole,3.00,3.0,4.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,1.0,2.0,3.0,1.0,1.0,4.0,durante un esame universitario
137,138,None,Di studio,24,Femmina,Centro Italia,5.00,5.0,5.0,4.0,5.0,5.0,5.0,4.0,1.0,5.0,1.0,5.0,5.0,5.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,1.0,1.0,5.0,2.0,4.0,1.0,5.0,esami
138,139,None,Entrambi,27,Femmina,Nord Italia,8.00,4.0,4.0,3.0,3.0,4.0,4.0,2.0,3.0,4.0,2.0,4.0,4.0,4.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,3.0,4.0,4.0,4.0,2.0,2.0,3.0,None
139,140,saraforno2004@gmail.com,Di studio,21,Femmina,Nord Italia,3.00,4.0,5.0,4.0,5.0,4.0,4.0,4.0,3.0,3.0,1.0,4.0,5.0,4.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,1.0,3.0,4.0,3.0,3.0,2.0,4.0,None
140,141,fede161202@gmail.com,Di studio,23,Maschio,Centro Italia,4.00,4.0,5.0,4.0,4.0,5.0,4.0,2.0,1.0,1.0,1.0,4.0,4.0,5.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,4.0,3.0,2.0,3.0,3.0,3.0,2.0,5.0,None
141,142,Preferisco non condividere,Di studio,21,Maschio,Nord Italia,3.00,4.0,5.0,3.0,4.0,5.0,5.0,4.0,4.0,3.0,2.0,4.0,5.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,5.0,Una situazione in cui sento maggiormente l'ans...
142,143,alessiabondanza408@gmail.com,Di studio,21,Femmina,Nord Italia,3.00,4.0,4.0,2.0,3.0,5.0,4.0,3.0,3.0,4.0,2.0,4.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,3.0,4.0,4.0,3.0,3.0,2.0,4.0,Prima degli esami ho tanta ansia e sintomi com...
143,144,None,Di studio,24,Maschio,Nord Italia,5.00,4.0,5.0,1.0,5.0,5.0,5.0,1.0,1.0,3.0,1.0,4.0,5.0,1.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,4.0,4.0,2.0,1.0,4.0,None
144,145,None,Di studio,25,Femmina,Nord Italia,5.00,4.0,4.0,2.0,5.0,5.0,2.0,2.0,1.0,4.0,4.0,3.0,4.0,4.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,2.0,4.0,3.0,1.0,4.0,2.0,3.0,2.0,4.0,Prima di un esame o di un'esposizione
145,146,None,Di studio,28,Femmina,Centro Italia,8.00,4.0,5.0,4.0,4.0,5.0,5.0,4.0,4.0,3.0,1.0,5.0,5.0,3.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,5.0,4.0,2.0,2.0,4.0,3.0,4.0,3.0,5.0,Esami orali o presentazioni
146,147,irene.bruini@gmail.com,Entrambi,29,Femmina,Nord Italia,11.00,5.0,3.0,3.0,4.0,3.0,4.0,2.0,3.0,5.0,5.0,5.0,3.0,3.0,3.0,4.0,4.0,4.0,5.0,5.0,5.0,3.0,3.0,2.0,3.0,1.0,4.0,3.0,3.0,4.0,Parlare di fronte a un pubblico
147,148,None,Di lavoro,30,Maschio,Nord Italia,15.00,2.0,3.0,4.0,4.0,3.0,3.0,2.0,3.0,4.0,5.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,3.0,1.0,2.0,2.0,4.0,1.0,1.0,2.0,2.0,4.0,4.0,Spiegare una cosa che non ho compreso a pieno
148,149,None,Di studio,23,Femmina,Nord Italia,5.00,4.0,4.0,2.0,2.0,5.0,5.0,1.0,1.0,5.0,1.0,4.0,4.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,2.0,2.0,4.0,2.0,2.0,2.0,5.0,None
149,150,giaggia126@icloud.com,Entrambi,19,Maschio,Centro Italia,1.00,3.0,2.0,1.0,2.0,4.0,2.0,1.0,1.0,2.0,1.0,2.0,3.0,2.0,4.0,1.0,2.0,5.0,4.0,5.0,2.0,3.0,3.0,2.0,2.0,4.0,4.0,2.0,2.0,3.0,None
150,151,None,Di lavoro,29,Femmina,Nord Italia,8.00,4.0,3.0,3.0,1.0,2.0,3.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,3.0,5.0,5.0,2.0,3.0,5.0,Parlare in pubblico
151,152,giuliabruini2@gmail.com,Studio ma sono alla ricerca di tirocinio/lavoro,24,Femmina,Nord Italia,5.00,4.0,4.0,3.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,3.0,4.0,2.0,1.0,2.0,3.0,5.0,3.0,5.0,None
152,153,None,Disoccupato,19,Preferisco non specificarlo,Nord Italia,0.00,5.0,4.0,5.0,3.0,5.0,5.0,3.0,4.0,2.0,3.0,5.0,5.0,4.0,3.0,5.0,4.0,4.0,5.0,3.0,5.0,3.0,4.0,2.0,3.0,1.0,2.0,5.0,5.0,5.0,"Parlare in pubblico, anche durante un confront..."
153,154,Gioperez2001@gmail.com,Di studio,24,Femmina,Nord Italia,6.00,2.0,3.0,2.0,4.0,2.0,4.0,3.0,3.0,3.0,2.0,3.0,3.0,4.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,3.0,3.0,4.0,4.0,4.0,4.0,2.0,3.0,3.0,No
154,155,None,Di lavoro,26,Maschio,Nord Italia,5.00,3.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,4.0,1.0,4.0,4.0,1.0,1.0,1.0,None
156,157,Lorenzo.briccola@hotmail.it,Di lavoro,30,Maschio,Nord Italia,11.00,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,1.0,1.0,1.0,5.0,2.0,3.0,5.0,1.0,1.0,2.0,None
158,159,None,Di lavoro,25,Femmina,Nord Italia,6.00,3.0,3.0,2.0,2.0,4.0,3.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,4.0,3.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,Riunioni
159,160,None,Di lavoro,30,Femmina,Nord Italia,10.00,3.0,3.0,3.0,5.0,5.0,3.0,3.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,3.0,4.0,2.0,1.0,3.0,3.0,5.0,5.0,2.0,2.0,3.0,None
160,161,None,Di lavoro,29,Femmina,Nord Italia,10.00,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,2.0,3.0,2.0,2.0,3.0,3.0,5.0,3.0,3.0,1.0,5.0,Situazioni in cui espongo in pubblico
163,164,None,Di lavoro,29,Maschio,Nord Italia,10.00,4.0,4.0,3.0,5.0,5.0,4.0,4.0,3.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,5.0,4.0,4.0,4.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,quando mi chiedono di portare a termine qualco...
164,165,giulio.serafini098@gmail.com,Di lavoro,27,Maschio,Centro Italia,8.00,3.0,4.0,2.0,3.0,2.0,4.0,3.0,4.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,4.0,3.0,2.0,2.0,4.0,None

Info DataFrame pulito:
<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 0 to 164
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               147 non-null    int64
 1   email            12 non-null     object
 2   contesto         147 non-null    object
 3   età              147 non-null    int64
 4   genere           147 non-null    object
 5   area_geo         147 non-null    object
 6   anni_esperienza  147 non-null    float64
 7   Item_1           147 non-null    float64
 8   Item_2           147 non-null    float64
 9   Item_3           147 non-null    float64
 10  Item_4           147 non-null    float64
 11  Item_5           147 non-null    float64
 12  Item_6           144 non-null    float64
 13  Item_7           144 non-null    float64
 14  Item_8           144 non-null    float64
 15  Item_9           145 non-null    float64
 16  Item_10          143 non-null    float64
 17  Item_11          93 non-null     float64
 18  Item_12          93 non-null     float64
 19  Item_13          92 non-null     float64
 20  Item_14          91 non-null     float64
 21  Item_15          91 non-null     float64
 22  Item_16          83 non-null     float64
 23  Item_17          83 non-null     float64
 24  Item_18          83 non-null     float64
 25  Item_19          83 non-null     float64
 26  Item_20          83 non-null     float64
 27  Item_21          147 non-null    float64
 28  Item_22          147 non-null    float64
 29  Item_23          147 non-null    float64
 30  Item_24          147 non-null    float64
 31  Item_25          147 non-null    float64
 32  Item_26          147 non-null    float64
 33  Item_27          147 non-null    float64
 34  Item_28          147 non-null    float64
 35  Item_29          147 non-null    float64
 36  Item_30          82 non-null     object
dtypes: float64(30), int64(2), object(5)
memory usage: 43.6+ KB

# Cella 13 - Salva in tabella clean_data:

In [62]:
# Connessione al database
conn = get_mysql_connection()
cursore = conn.cursor()

# Crea tabella clean_data
cursore.execute("DROP TABLE IF EXISTS clean_data")

query_crea_tabella = """
CREATE TABLE clean_data (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    email               VARCHAR(255),
    contesto            VARCHAR(255),
    età                 INT,
    genere              VARCHAR(50),
    area_geo            VARCHAR(100),
    anni_esperienza     DECIMAL(5,2),
    Item_1              INT,
    Item_2              INT,
    Item_3              INT,
    Item_4              INT,
    Item_5              INT,
    Item_6              INT,
    Item_7              INT,
    Item_8              INT,
    Item_9              INT,
    Item_10             INT,
    Item_11             INT,
    Item_12             INT,
    Item_13             INT,
    Item_14             INT,
    Item_15             INT,
    Item_16             INT,
    Item_17             INT,
    Item_18             INT,
    Item_19             INT,
    Item_20             INT,
    Item_21             INT,
    Item_22             INT,
    Item_23             INT,
    Item_24             INT,
    Item_25             INT,
    Item_26             INT,
    Item_27             INT,
    Item_28             INT,
    Item_29             INT,
    Item_30             TEXT,
    UNIQUE KEY unique_email (email)
)
"""

cursore.execute(query_crea_tabella)
conn.commit()
print("Tabella clean_data creata!")

# Prepara DataFrame per inserimento
df_clean_to_save = df_clean.drop(columns=['id']) if 'id' in df_clean.columns else df_clean

# CONVERSIONE CORRETTA: NaN → None E numpy types → Python types
df_clean_to_save = df_clean_to_save.replace({np.nan: None})  # NaN → None

# Prepara query di inserimento
colonne = df_clean_to_save.columns.tolist()
placeholders = ', '.join(['%s'] * len(colonne))
colonne_str = ', '.join(colonne)

query_insert = f"INSERT INTO clean_data ({colonne_str}) VALUES ({placeholders})"

# Inserisci i dati
inserite = 0
errori = 0

for idx, row in df_clean_to_save.iterrows():
    try:
        # Converti valori numpy in tipi Python nativi
        valori = tuple(
            None if pd.isna(v) else (
                int(v) if isinstance(v, (np.integer, np.int64)) else
                float(v) if isinstance(v, (np.floating, np.float64)) else
                v
            )
            for v in row
        )
        
        cursore.execute(query_insert, valori)
        inserite += 1
        
        conn.commit()
    except Exception as e:
        print(f"Errore riga {idx}: {e}")
        errori += 1

conn.commit()
print(f"\nInserimento completato!")
print(f"   - Righe inserite: {inserite}")
print(f"   - Errori: {errori}")

cursore.close()
conn.close()

Tabella clean_data creata!

Inserimento completato!
   - Righe inserite: 147
   - Errori: 0